version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
        - "5432:5432"
    restart: always
  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  app:
    image: django:latest
    container_name: web
    build:
      context: .
      dockerfile: ./django/Dockerfile
    volumes:
      - static_data:/vol/web
    environment:
      - DEBUG=1
      - SECRET_KEY=je+702%ye)y3g@@gji3e6&!&*^b-as9jvbbml(45lt6p9wv(&8
      - ALLOWED_HOSTS=127.0.0.1,localhost
    depends_on:
      - db
      - redis
    restart: always
  proxy:
    image: nginx:latest
    container_name: proxy
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static_data:/vol/static  
    ports:
      - "8080:8080"
    depends_on:
      - app
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
volumes:
  static_data: